---
abstract: 'Wikibase data types struct conversions.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
  Test::Shared::Fixture::Wikibase::Datatype::Lexeme::Wikidata::DogCzechNoun: 0.19
  Test::Shared::Fixture::Wikibase::Datatype::Property::Wikidata::InstanceOf: 0.17
  Unicode::UTF8: 0
  Wikibase::Datatype::Item: 0
  Wikibase::Datatype::Lexeme: 0.25
  Wikibase::Datatype::Mediainfo: 0
  Wikibase::Datatype::MediainfoSnak: 0
  Wikibase::Datatype::MediainfoStatement: 0
  Wikibase::Datatype::Property: 0.25
  Wikibase::Datatype::Reference: 0
  Wikibase::Datatype::Sitelink: 0
  Wikibase::Datatype::Snak: 0.32
  Wikibase::Datatype::Statement: 0
  Wikibase::Datatype::Value::Globecoordinate: 0
  Wikibase::Datatype::Value::Item: 0
  Wikibase::Datatype::Value::Lexeme: 0
  Wikibase::Datatype::Value::Monolingual: 0
  Wikibase::Datatype::Value::Property: 0
  Wikibase::Datatype::Value::Quantity: 0
  Wikibase::Datatype::Value::Sense: 0.29
  Wikibase::Datatype::Value::String: 0
  Wikibase::Datatype::Value::Time: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wikibase-Datatype-Struct
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  English: 0
  Error::Pure: 0.15
  Exporter: 0
  List::Util: 1.33
  Readonly: 0
  URI: 0
  Wikibase::Datatype::Form: 0
  Wikibase::Datatype::Item: 0
  Wikibase::Datatype::Lexeme: 0
  Wikibase::Datatype::Mediainfo: 0
  Wikibase::Datatype::MediainfoSnak: 0
  Wikibase::Datatype::MediainfoStatement: 0
  Wikibase::Datatype::Property: 0
  Wikibase::Datatype::Reference: 0
  Wikibase::Datatype::Sense: 0
  Wikibase::Datatype::Sitelink: 0
  Wikibase::Datatype::Snak: 0.32
  Wikibase::Datatype::Statement: 0
  Wikibase::Datatype::Value: 0.29
  Wikibase::Datatype::Value::Globecoordinate: 0
  Wikibase::Datatype::Value::Item: 0
  Wikibase::Datatype::Value::Lexeme: 0
  Wikibase::Datatype::Value::Monolingual: 0
  Wikibase::Datatype::Value::Property: 0
  Wikibase::Datatype::Value::Quantity: 0
  Wikibase::Datatype::Value::Sense: 0.29
  Wikibase::Datatype::Value::String: 0
  Wikibase::Datatype::Value::Time: 0
  perl: 5.01
resources:
  bugtracker: https://github.com/michal-josef-spacek/Wikibase-Datatype-Struct/issues
  homepage: https://github.com/michal-josef-spacek/Wikibase-Datatype-Struct
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Wikibase-Datatype-Struct
version: '0.14'
